'use strict';
/**
 * Records with translated fields.
 */
module.exports = {
    'ACTI': ['FULL', 'RNAM'],
    'ALCH': ['FULL'],
    'AMMO': ['FULL'],
    'APPA': ['FULL'],
    'ARMO': ['DESC', 'FULL'],
    'AVIF': ['DESC', 'FULL'],
    'BOOK': ['CNAM', 'DESC', 'FULL'],
    'BPTD': ['BPTN'],
    'CELL': ['FULL'],
    'CLAS': ['FULL'],
    'CLFM': ['FULL'],
    'COLL': ['DESC'],
    'CONT': ['FULL'],
    'DIAL': ['FULL'],
    'DOOR': ['FULL'],
    'ENCH': ['FULL'],
    'EXPL': ['FULL'],
    'EYES': ['FULL'],
    'FACT': ['FNAM', 'FULL', 'MNAM'],
    'FLOR': ['FULL', 'RNAM'],
    'FURN': ['FULL'],
    'GMST': ['DATA'],
    'HAZD': ['FULL'],
    'HDPT': ['FULL'],
    'INFO': ['NAM1', 'RNAM'],
    'INGR': ['FULL'],
    'KEYM': ['FULL'],
    'LCTN': ['FULL'],
    'LIGH': ['FULL'],
    'LSCR': ['DESC'],
    'MESG': ['DESC', 'FULL', 'ITXT'],
    'MGEF': ['DNAM', 'FULL'],
    'MISC': ['FULL'],
    'NPC_': ['FULL', 'SHRT'],
    'PERK': ['DESC', 'EPF2', 'EPFD', 'FULL'],
    'PROJ': ['FULL'],
    'QUST': ['CNAM', 'FULL', 'NNAM'],
    'RACE': ['DESC', 'FULL'],
    'REFR': ['FULL'],
    'REGN': ['RDMP'],
    'SCRL': ['DESC', 'FULL'],
    'SHOU': ['DESC', 'FULL'],
    'SLGM': ['FULL'],
    'SNCT': ['FULL'],
    'SPEL': ['DESC', 'FULL'],
    'TACT': ['FULL'],
    'TREE': ['FULL'],
    'WATR': ['FULL'],
    'WEAP': ['DESC', 'FULL'],
    'WOOP': ['FULL', 'TNAM'],
    'WRLD': ['FULL'],
};
